const fs=require("fs"),path=require("path");
const ROOT=__dirname,OUT=path.join(ROOT,"dist"),SITE="https://minetools.io";
const copy=(a,b)=>{fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(a,b)};
const write=(p,c)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,c)};
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const clean=s=>String(s??"").replace(/\s+/g," ").trim();
const loaders=["fabric","forge","neoforge"];
const curatedVersions=["1.21.1","1.21","1.20.1","1.19.2"];
const curatedCategories=[{slug:"optimization",label:"Performance & Optimization",match:["optimization","performance"]},{slug:"technology",label:"Technology",match:["technology"]},{slug:"adventure",label:"Adventure",match:["adventure"]},{slug:"utility",label:"Utility & QoL",match:["utility","management","game-mechanics"]}];
const tools=[{src:"stack-calculator.html",slug:"stack-calculator"},{src:"nether-portal-calculator.html",slug:"nether-portal-calculator"},{src:"ram-calculator.html",slug:"ram-calculator"}];
async function getMods(){try{const facets=encodeURIComponent(JSON.stringify([["project_type:mod"]]));const r=await fetch("https://api.modrinth.com/v2/search?limit=100&index=downloads&facets="+facets,{headers:{"User-Agent":"MineTools/2.1 (https://minetools.io)"}});if(!r.ok)throw new Error("HTTP "+r.status);const j=await r.json();return j.hits.filter(m=>m.slug&&m.title).map(m=>({...m,description:clean(m.description),categories:m.categories||[],display_categories:m.display_categories||[],versions:m.versions||[]}))}catch(e){console.warn("Modrinth unavailable; using seed:",e.message);return JSON.parse(fs.readFileSync(path.join(ROOT,"data","seed.json"),"utf8"))}}
function head(title,desc,canonical,robots="index,follow",schema=""){return '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(desc)+'"><link rel="canonical" href="'+canonical+'"><meta name="robots" content="'+robots+'"><meta property="og:type" content="website"><meta property="og:site_name" content="MineTools"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(desc)+'"><meta property="og:url" content="'+canonical+'"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/assets/styles.css">'+(schema?'<script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,"\\u003c")+'</script>':"")}
function header(){return '<header class="site-header"><div class="container nav"><a class="brand" href="/">Mine<span>Tools</span></a><nav class="navlinks" aria-label="Primary"><a href="/tools/">Tools</a><a href="/tools/stack-calculator/">Stack Calculator</a><a href="/tools/nether-portal-calculator/">Nether Coordinates</a><a href="/tools/ram-calculator/">RAM Calculator</a></nav></div></header>'}
function footer(){return '<footer class="footer"><div class="container footer-row"><div>© 2026 MineTools · Not affiliated with Mojang Studios or Microsoft.</div><div><a href="/tools/">Tools</a><a href="/mods/">Mod Index</a><a href="/privacy/">Privacy</a></div></div></footer>'}
function shell(title,desc,canonical,body,schema){return '<!doctype html><html lang="en"><head>'+head(title,desc,canonical,"index,follow",schema)+'</head><body>'+header()+body+footer()+'<script src="/assets/app.js" defer></script></body></html>'}
function breadcrumb(items){return '<nav class="breadcrumbs" aria-label="Breadcrumb">'+items.map((x,i)=>i===items.length-1?'<span>'+esc(x[0])+'</span>':'<a href="'+x[1]+'">'+esc(x[0])+'</a>').join(" / ")+'</nav>'}
function modPage(m){const availableLoaders=loaders.filter(l=>(m.categories||[]).includes(l));if((m.categories||[]).includes("quilt"))availableLoaders.push("quilt");const versions=(m.versions||[]).slice().reverse().slice(0,16);const desc=clean(m.description)||("Version and loader information for the "+m.title+" Minecraft mod.");const canonical=SITE+"/mods/"+m.slug+"/";const body='<main class="container detail">'+breadcrumb([["Home","/"],["Mods","/mods/"],[m.title]])+'<div class="mod-hero"><article class="mod-summary"><div class="identity"><img class="mod-icon" src="'+(m.icon_url||"/assets/mod-placeholder.svg")+'" alt="'+esc(m.title)+' icon" width="92" height="92"><div><h1>'+esc(m.title)+' Minecraft Mod</h1><p>by '+esc(m.author||"Unknown")+'</p></div></div><p class="description">'+esc(desc)+'</p><div class="notice">The mod index is a supporting feature. MineTools does not re-host mod files.</div></article><aside class="sidebox"><h2>Project source</h2><a class="btn btn-primary" target="_blank" rel="nofollow noopener noreferrer" href="https://modrinth.com/mod/'+encodeURIComponent(m.slug)+'">VIEW SOURCE</a></aside></div></main>';return shell(m.title+" Minecraft Mod | MineTools",desc,canonical,body)}
function card(m){return '<a class="mod-card" href="/mods/'+m.slug+'/"><div class="mod-top"><img class="mod-icon" loading="lazy" src="'+(m.icon_url||"/assets/mod-placeholder.svg")+'" alt="'+esc(m.title)+' icon" width="52" height="52"><div><h3>'+esc(m.title)+'</h3><div class="author">by '+esc(m.author||"Unknown")+'</div></div></div><p>'+esc(m.description)+'</p></a>'}
function landing(title,desc,canonical,mods,crumb){const body='<main class="container detail">'+breadcrumb([["Home","/"],crumb])+'<section class="landing-intro"><h1>'+esc(title)+'</h1><p>'+esc(desc)+'</p><div class="landing-count">'+mods.length+' indexed mods</div></section><section class="section"><div class="mod-grid">'+(mods.length?mods.slice(0,48).map(card).join(""):'<div class="empty" style="grid-column:1/-1">No indexed mods matched this page.</div>')+'</div></section></main>';return shell(title+" | MineTools",desc,canonical,body)}
(async()=>{fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});for(const p of ["index.html","robots.txt"])copy(path.join(ROOT,p),path.join(OUT,p));for(const p of ["styles.css","app.js","mod-placeholder.svg"])copy(path.join(ROOT,"assets",p),path.join(OUT,"assets",p));for(const [src,dst] of [["mods.html","mods/index.html"],["tools.html","tools/index.html"],["privacy.html","privacy/index.html"],["404.html","404.html"]])copy(path.join(ROOT,"pages",src),path.join(OUT,dst));for(const t of tools)copy(path.join(ROOT,"pages","tools",t.src),path.join(OUT,"tools",t.slug,"index.html"));
const mods=await getMods();write(path.join(OUT,"data","mods.json"),JSON.stringify(mods));for(const m of mods)write(path.join(OUT,"mods",m.slug,"index.html"),modPage(m));
for(const l of loaders){const x=mods.filter(m=>(m.categories||[]).includes(l));write(path.join(OUT,"loaders",l,"index.html"),landing(l[0].toUpperCase()+l.slice(1)+" Minecraft Mods","Browse "+l+" Minecraft mods as a supporting project index.",SITE+"/loaders/"+l+"/",x,[l+" Mods"]))}
for(const v of curatedVersions){const slug=v.replaceAll(".","-")+"-mods",x=mods.filter(m=>(m.versions||[]).includes(v));write(path.join(OUT,"minecraft",slug,"index.html"),landing("Minecraft "+v+" Mods","Browse indexed projects listing Minecraft "+v+" support.",SITE+"/minecraft/"+slug+"/",x,["Minecraft "+v+" Mods"]))}
for(const c of curatedCategories){const x=mods.filter(m=>c.match.some(k=>(m.categories||[]).includes(k)||(m.display_categories||[]).includes(k)));write(path.join(OUT,"categories",c.slug,"index.html"),landing(c.label+" Minecraft Mods","Browse indexed "+c.label.toLowerCase()+" projects.",SITE+"/categories/"+c.slug+"/",x,[c.label]))}
const urls=["/","/tools/",...tools.map(t=>"/tools/"+t.slug+"/"),"/mods/","/privacy/",...mods.map(m=>"/mods/"+m.slug+"/"),...loaders.map(l=>"/loaders/"+l+"/"),...curatedVersions.map(v=>"/minecraft/"+v.replaceAll(".","-")+"-mods/"),...curatedCategories.map(c=>"/categories/"+c.slug+"/")];write(path.join(OUT,"sitemap.xml"),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+SITE+u+'</loc></url>').join("")+'</urlset>');console.log("MineTools tools-first build:",mods.length,"supporting mods,",tools.length,"live tools,",urls.length,"indexable URLs");})();